#!/bin/bash
# email-users.sh, v1.0
# Author: F. Michel, CNRS I3S, biomed VO support

help()
{   
  echo 
  echo "This script uses the files generated by monitor-se-space.sh and generates"
  echo "files that can be used by VO support shifters to send emails to heavy users"
  echo "of most loaded SEs."
  echo
  echo "Usage:"
  echo "$0 [-h|--help]"
  echo "$0 [--vo <VO>] --input-dir <directory> [--output-dir <directory>]"
  echo
  echo "  --vo <VO>: the Virtual Organisation. Defaults to biomed."
  echo
  echo "  --input-dir <idirectory>: relative name of the directory containing files <SE_hostname>_users"
  echo "                            generated by the monitor-se-space.sh script (e.g. 20111122-121434)."
  echo "                            Defaults to '.'".
  echo
  echo "  --output-dir <idirectory>: directory where to write result files."
  echo "                             Defaults to the same as the input dir."
  echo
  echo "  -h, --help: display this help"
  echo
  exit 1
}

VO=biomed 

INDIR=.
OUTDIR=.

# Check parameters
while [ ! -z "$1" ]
do
  case "$1" in
    --vo ) VO=$2; shift;;
    --input-dir ) INDIR=$2; shift;;
    --output-dir ) OUTDIR=$2; shift;;
    -h | --help ) help;;
    *) ;;
  esac
  shift
done

mkdir -p $OUTDIR
mkdir -p $OUTDIR/$INDIR

# Loop on all files "$INDIR/<SE hostname>_users", and for each generate file $OUTDIR/<SE hostname>_email
for FILE in `ls $INDIR/*_users`; do
  SEHOSTNAME=`echo $FILE | sed "s/_users//"i | cut -d"/" -f2`
  OUTNAME=$OUTDIR/`echo $FILE | sed "s/_users//"`_email
  echo -n "" > $OUTNAME

  echo -n "TO: biomed-technical-shifts@healthgrid.org;" >> $OUTNAME
  awk --field-separator "|" '{ printf " %s;",$2 }' $FILE >> $OUTNAME
  echo >> $OUTNAME
  cat <<EOF >> $OUTNAME

SUBJECT: SE $SEHOSTNAME is full, please clean up or migrate your files

Dear $VO VO user,

You have stored more than 1 GB of files on SE $SEHOSTNAME, which is almost full.
Please take some time to cleanup files you no longer need, or migrate them to some other SE. The list below shows all users with more than 1 GB on that SE.

Please don't hesitate to contact us (biomed-technical-shifts@healthgrid.org) in case you experience difficulties in this process.

Also, note that it is not recommended to try to move many files in parallel: due to scalability issues of the SE, only a limited number of concurrent connections can be initiated.

Thanks in advance,
   The $VO technical support team.

EOF

  echo "Creating file $OUTNAME"
  echo "#----------------------------------------------------------------------------------" >> $OUTNAME
  echo "# User's DN                                                         Used space (GB)" >> $OUTNAME
  awk --field-separator "|" '{ printf "%-70s %11s\n",$1,$3; }' $FILE >> $OUTNAME

done


