# This script parses the result previously generated by se-space-check.sh
# in order to make the sums of each column.

BEGIN { avail=0; used=0; total=0; }

{ avail+=$2; used+=$3; total+=$4 }

END { 
  # Avoid division by 0 error
  if (total==0) {total = 1}; 

  print "#_Total(TB)", avail/1000, used/1000, total/1000, int(used*100/total); 
}

