#!/bin/bash
# list-voms-users.sh, v1.0
# Author: F. Michel, CNRS I3S, biomed VO support

VO=biomed
VOMS_HOST=voms-biomed.in2p3.fr
VOMS_PORT=8443
VOMS_USERS=`pwd`/voms-users.txt
VOMS_SUSPENDED_EXPIRED_USERS=`pwd`/suspended-expired-voms-users.txt
help()
{
  echo
  echo "This script gets the list of active users only from the VOMS server using the voms-admin command."
  echo "It requires the file containing the suspended or expired users generated by the script list-suspended-expired-voms-users.sh"
  echo "The result file is replaced/created only if the voms-admin commands succeeds, otherwise "
  echo "the existing file remains unchanged."
  echo
  echo "Usage:"
  echo "$0 [-h|--help]"
  echo "$0 [--vo <VO>] [--voms-host <hostname>] [--voms-port <port>] [--out  <file name>]"
  echo
  echo "  --vo <VO>: the Virtual Organisation to query. Defaults to biomed."
  echo
  echo "  --voms-host <hostname>: VOMS server hostname. Defaults to voms-biomed.in2p3.fr."
  echo
  echo "  --voms-port <post>: VOMS server hostname. Defaults to 8443."
  echo
  echo "  --suspended-expired-voms-users <filename>: list of suspended or expired users."
  echo
  echo "  --out <file name>: where to store results. Defaults to './voms-users.txt'."
  echo
  echo "  -h, --help: display this help"
  echo
  exit 1
}



# Check parameters
while [ ! -z "$1" ]
do
  case "$1" in
    --vo ) VO=$2; shift;;
    --out ) VOMS_USERS=$2; shift;;
    --voms-host ) VOMS_HOST=$2; shift;;
    --voms-port ) VOMS_PORT=$2; shift;;
    --suspended-expired-voms-users ) VOMS_SUSPENDED_EXPIRED_USERS=$2; shift;;
    -h | --help ) help;;
    *) help;;
  esac
  shift
done

# Get the current list of users from the VOMS server
voms-admin --vo=$VO --host $VOMS_HOST --port $VOMS_PORT list-users > $VOMS_USERS.temp
cat $VOMS_SUSPENDED_EXPIRED_USERS | while read line 
do
    dn=`echo "$line" | cut -d ',' -f 1`  
    grep -v "$dn" $VOMS_USERS.temp > $VOMS_USERS.aux.temp
    cat $VOMS_USERS.aux.temp > $VOMS_USERS.temp
done

if test -f $VOMS_USERS.temp; then
    cp $VOMS_USERS.temp $VOMS_USERS
    rm $VOMS_USERS.aux.temp
    rm $VOMS_USERS.temp
    echo "Users list built successfully: $VOMS_USERS."
    exit 0
else
    echo "Failed to build list of users from VOMS."
    exit 1
fi

