#!/bin/bash
# unknwon-users.sh, v1.0
# Author: F. Michel, CNRS I3S, biomed VO support

help()
{   
  echo 
  echo "This script uses the files generated by scan-se.sh and generates"
  echo "files that can be used by VO support shifters to send emails to heavy users"
  echo "of most loaded SEs."
  echo
  echo "Usage:"
  echo "$0 [-h|--help]"
  echo "$0 [--vo <VO>] --input-dir <directory>"
  echo
  echo "  --vo <VO>: the Virtual Organisation. Defaults to biomed."
  echo
  echo "  --input-dir <directory>: name of the work directory containing files <SE_hostname>_unknown"
  echo "                           generated by the scan-se.sh script (e.g. /tmp/monitor-se/20111122-121434)."
  echo "                           Defaults to '.'".
  echo
  echo "  -h, --help: display this help"
  echo
  exit 1
}

VO=biomed 
INDIR=.

NOW=`date "+%Y%m%d-%H%M%S"`
TMPFILE=/tmp/monitor-se-unknown-users-${NOW}.tmp

# Check parameters
while [ ! -z "$1" ]
do
  case "$1" in
    --vo ) VO=$2; shift;;
    --input-dir ) INDIR=$2; shift;;
    -h | --help ) help;;
    *) ;;
  esac
  shift
done

# Loop on all files "$INDIR/<SE hostname>_unknown"
echo -n "" > $TMPFILE
for FILE in `ls $INDIR/*_unknown`; do
  cat $FILE | cut -d '|' -f1 >> $TMPFILE
done

cat $TMPFILE | sort | uniq

rm $TMPFILE

