#!/usr/bin/python

CSV_DELIMITER = "notinitialized"
DEBUG = ""
DATA_DIR = "notinitialized"
FROM_DATE = "notinitialized"
TO_DATE = "notinitialized"
DECIMAL_MARK = "notinitialized"
OUTPUT_DIR = "notinitialized"
MONCE = "notinitialized"
RUN_RUNNING_RATIO = "notinitialized"
RUN_RUNNING_RATIO_DAILY = "notinitialized"
RUN_RUNNING_RATIO_DAY_NIGHT = "notinitialized"
RUN_DISTRIBUTE_CE_BY_RUNNING_RATIO = "notinitialized"
RUN_RUNNING_RATIO_SLICES = "notinitialized"
RUN_RUNNING_RATIO_BAD = "notinitialized"
RUN_RUNNING_RATIO_PER_CE = "notinitialized"
STDOUT = "notinitialized"
SEPARATOR = "#SEPARATOR#"
PERCENT = "notinitialized"
